let mapleader = " "
syntax on

set number
set norelativenumber
set cursorline
set wrap
set showcmd
set wildmenu
set hlsearch
set incsearch
set ignorecase
set smartcase
exec "nohlsearch"


noremap <LEADER><CR> :nohlsearch<CR>
map R :source $MYVIMRC<CR>
map s <nop>
map S :w<CR>
map Q :q<CR>


call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'connorholyday/vim-snazzy'
Plug 'mg979/vim-visual-multi', {'branch': 'master'}

call plug#end()

color snazzy
let g:SnazzyTransparent = 1
